### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by oodegard** [tischi/fiji-plugin-yaml-metadata#2]
I installed the EMBL-CBA, restarted imageJ, opened an image and pressed create YAML data.

Then I recieved this error...

Am I missing some library?

(Fiji Is Just) ImageJ 2.0.0-rc-68/1.52e; Java 1.8.0_66 [64-bit]; Windows 10 10.0; 2259MB of 12177MB (18%)
 
java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/JsonFactory
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.newInstance(Class.java:412)
	at org.scijava.plugin.PluginInfo.createInstance(PluginInfo.java:306)
	at org.scijava.command.CommandInfo.createInstance(CommandInfo.java:250)
	at org.scijava.command.CommandModule.instantiateCommand(CommandModule.java:251)
	at org.scijava.command.CommandModule.<init>(CommandModule.java:101)
	at org.scijava.command.CommandInfo.createModule(CommandInfo.java:328)
	at org.scijava.module.DefaultModuleService.createModule(DefaultModuleService.java:170)
	at org.scijava.module.DefaultModuleService.run(DefaultModuleService.java:209)
	at org.scijava.module.DefaultModuleService.run(DefaultModuleService.java:200)
	at org.scijava.module.DefaultModuleService.run(DefaultModuleService.java:185)
	at org.scijava.command.DefaultCommandService.run(DefaultCommandService.java:186)
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:298)
	at net.imagej.legacy.DefaultLegacyHooks.interceptRunPlugIn(DefaultLegacyHooks.java:163)
	at ij.IJ.runPlugIn(IJ.java)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:66)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.core.JsonFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 20 more

**Comment by tischi** [comment]
fixed.
https://github.com/tischi/fiji-plugin-yaml-metadata/commit/0a16d6d15cac00d265099411cc2be23714366a7f
