### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by oodegard** [tischi/fiji-plugin-yaml-metadata#6]
I have some trouble running the metadata generator on spinning disk confocal image (from micromanager). 

The error I get is:

MicromanagerReader initializing C:\Users\Ellenberg Lab\OneDrive\Transfer\#225_filetransfer\180905\180905_225_ibidi1_B\Pos0\img_000000000_Default_000.tif
Reading metadata file
Populating metadata
Finding image file names
Building list of TIFFs
[ERROR] Module threw exception
java.lang.NullPointerException
	at de.embl.cba.metadata.Metadata.addPhysicalDimensions(Metadata.java:91)
	at de.embl.cba.metadata.Metadata.populateMetadataMap(Metadata.java:74)
	at de.embl.cba.metadata.Metadata.<init>(Metadata.java:39)
	at de.embl.cba.metadata.MetadataCommand.run(MetadataCommand.java:45)
	at org.scijava.command.CommandModule.run(CommandModule.java:199)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService$3.call(DefaultThreadService.java:238)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by tischi** [comment]
fixed in https://github.com/tischi/fiji-plugin-yaml-metadata/commit/4a26d23206837378b6260c119ab58f64bb57ed24
